### ISSUE TITLE
OneWireViewer

### ISSUE THREAD

**Issue by dev11111** [concord-consortium/BlockModel#1]
Hi,

I am trying to run onewireviewer on netbeans but I am not able to display the last page i.e device list when I click on finish the whole gui disappears.It was working few days before I donno what happened now its not working.I have not made any changes in code I just added resource package for the images as I was getting null pointer execption.Pls help me bring up the final page.Using lastest netbeans & java jdk 1.8.

Regards,
dev

**Comment by scytacki** [comment]
The version of the one wire SDK included in this repository is around 15 years old.  I recommend using the newest one wire SDK here:
https://www.maximintegrated.com/en/products/ibutton/software/1wire/1wire_api.cfm
